## Headless test runner (ADR-0010). Run from the repo root with:
##   godot --headless --path game --script res://tests/run_tests.gd
## Exits with code 0 if every test passed, 1 otherwise — CI treats a
## non-zero exit as a failed build (.github/workflows/ci.yml).
##
## Uses explicit preload() for the test files rather than bare global
## class_name references, so at least loading this file never fails with
## "Identifier not declared" on a checkout whose global script class cache
## hasn't been built yet (.godot/global_script_class_cache.cfg, only
## generated by a full editor filesystem scan — a plain `--script`
## invocation does not build it). This does NOT cover the test files' own
## internal references to core/ classes (TacticalGrid, AStarPathfinder, ...)
## — those still need the cache warm, which is why CI runs a
## `godot --headless --path game --import` step before this script.
extends SceneTree

const TestReporterScript := preload("res://tests/test_reporter.gd")
const TestPathfindingScript := preload("res://tests/test_pathfinding.gd")
const TestCombatRPSScript := preload("res://tests/test_combat_rps.gd")
const TestEconomyScript := preload("res://tests/test_economy.gd")
const TestProcgenDeterminismScript := preload("res://tests/test_procgen_determinism.gd")
const TestSaveLoadRoundtripScript := preload("res://tests/test_save_load_roundtrip.gd")

func _initialize() -> void:
	var reporter = TestReporterScript.new()

	TestPathfindingScript.run(reporter)
	TestCombatRPSScript.run(reporter)
	TestEconomyScript.run(reporter)
	TestProcgenDeterminismScript.run(reporter)
	TestSaveLoadRoundtripScript.run(reporter)

	reporter.print_summary()
	quit(0 if reporter.all_passed() else 1)
